exec(open('tests/smoke.py').read().split("assert request(op='open'")[0])
request(op='open',path=':memory:')
sql('SELECT (1,NULL,3)=(1,2,4),(1,NULL,3)=(1,2,3),(1,2)<(2,NULL),(1,NULL) IS (1,NULL)',[[0,None,1,1]])
sql('SELECT (1,2) IN ((1,2),(3,4)),(1,NULL) IN ((2,NULL),(3,4)),NULL IN (),NULL NOT IN ()',[[1,0,0,1]])
sql('CREATE TABLE af(t TEXT,n NUMERIC,i INT,r REAL,b BLOB)')
sql("INSERT INTO af VALUES('500.0','500.0','500.0','500.0','500.0')")
sql('SELECT typeof(t),typeof(n),typeof(i),typeof(r),typeof(b) FROM af',[['text','integer','integer','real','text']])
sql("SELECT t=500.0,n='500',+n='500',b=500,b='500.0' FROM af",[[1,1,0,0,1]])
sql('CREATE TABLE nc(x TEXT COLLATE NOCASE UNIQUE)')
sql("INSERT INTO nc VALUES('Foo'),('bar')")
sql("SELECT x FROM nc WHERE x='foo'",[['Foo']])
sql("INSERT INTO nc VALUES('fOO')",error=True)
sql("SELECT x FROM nc ORDER BY x",[['bar'],['Foo']])
sql("SELECT x FROM nc ORDER BY x COLLATE BINARY",[['Foo'],['bar']])
sql('CREATE TABLE l(a,b)');sql('CREATE TABLE r(a,c)')
sql("INSERT INTO l VALUES(1,'x'),(2,'y')");sql("INSERT INTO r VALUES(2,'z'),(3,'q')")
sql('SELECT * FROM l FULL JOIN r USING(a) ORDER BY a',[[1,'x',None],[2,'y','z'],[3,None,'q']])
sql('SELECT * FROM l NATURAL JOIN r',[[2,'y','z']])
sql('SELECT name,type FROM pragma_table_info(\'af\') ORDER BY cid',[['t','TEXT'],['n','NUMERIC'],['i','INT'],['r','REAL'],['b','BLOB']])
sql("SELECT key,value,type FROM json_each('[1,\"x\",null]')",[[0,1,'integer'],[1,'x','text'],[2,None,'null']])
sql('CREATE TABLE j(x)');sql("INSERT INTO j VALUES('[1,2]'),('[3]')")
sql('SELECT value FROM j,json_each(j.x)',[[1],[2],[3]])
sql('WITH v(x) AS (VALUES(10),(20)) INSERT INTO l SELECT x,x*2 FROM v')
sql('SELECT a,b FROM l WHERE a>5 ORDER BY a',[[10,20],[20,40]])
sql('WITH v(x) AS (VALUES(10)) UPDATE l SET b=99 WHERE a IN (SELECT x FROM v)')
sql('SELECT b FROM l WHERE a=10',[[99]])
sql('UPDATE l SET (a,b)=(SELECT 100,200) WHERE a=20')
sql('SELECT a,b FROM l WHERE a=100',[[100,200]])
sql('PRAGMA foreign_keys=ON')
sql('CREATE TABLE parent(k INTEGER PRIMARY KEY)');sql('CREATE TABLE child(k REFERENCES parent ON UPDATE CASCADE ON DELETE SET NULL)')
sql('INSERT INTO parent VALUES(1)');sql('INSERT INTO child VALUES(1)')
sql('UPDATE parent SET k=2 WHERE k=1');sql('SELECT * FROM child',[[2]])
sql('DELETE FROM parent');sql('SELECT * FROM child',[[None]])
sql('CREATE TABLE deferred(k REFERENCES parent DEFERRABLE INITIALLY DEFERRED)')
sql('BEGIN');sql('INSERT INTO deferred VALUES(7)');sql('COMMIT',error=True);sql('INSERT INTO parent VALUES(7)');sql('COMMIT')
sql('PRAGMA foreign_key_check',[])
print('semantics tests passed');p.terminate()
