"""Process-level regression tests derived from /docs (no reference engine)."""
import json, subprocess, os, sys
BIN=os.environ.get('SQLITE_AGENT_BIN','/work/target/debug/sqlite-agent')
p=subprocess.Popen([BIN],stdin=subprocess.PIPE,stdout=subprocess.PIPE,text=True)
n=0

def request(v):
    p.stdin.write(json.dumps(v)+'\n');p.stdin.flush()
    r=json.loads(p.stdout.readline())
    assert not r.get('ok') or all(len(row)==len(r['columns']) for row in r['rows']),r
    return r

def execute(s): return request({'op':'execute','sql':s})
def ok(s):
    global n
    r=execute(s);n+=1;assert r['ok'],(s,r);return r

def err(s):
    global n
    r=execute(s);n+=1;assert not r['ok'],(s,r);return r

def check(s,expected,types=None,columns=None):
    r=ok(s)
    actual=[[None if x['type']=='null' else x['value'] for x in row] for row in r['rows']]
    expected=[[None if x is None else str(x) for x in row] for row in expected]
    assert actual==expected,(s,actual,expected)
    if types: assert [[x['type'] for x in row] for row in r['rows']]==types,(s,r,types)
    if columns is not None: assert r['columns']==columns,(s,r,columns)

assert not execute('SELECT 1')['ok']
request({'op':'open','path':':memory:'})
check("SELECT 1+2*3, 5/2, 5/2.0, -5%2, 1<<4, ~1, 'a'||'b'",[[7,2,'2.5',-1,16,-2,'ab']])
check("SELECT NULL=1, NULL=NULL, NULL IS NULL, NULL IS NOT NULL, NULL AND 0, NULL OR 1, NULL OR 0",[[None,None,1,0,0,1,None]])
check("SELECT 1 IN (), NULL IN (), NULL NOT IN (), 3 IN (1,NULL), 1 IN (1,NULL), 3 NOT IN (1,NULL)",[[0,0,1,None,1,None]])
check("SELECT '12' = 12, CAST('12' AS NUMERIC)=12, typeof(CAST('3.0e+5' AS NUMERIC)),CAST('123e5' AS INTEGER), CAST('abc' AS REAL)",[[0,1,'integer',123,'0.0']])
check("SELECT 0xFFFFFFFFFFFFFFFF, -9223372036854775808, typeof(9223372036854775807+1), 1/0, 1%0",[[-1,-9223372036854775808,'real',None,None]])
check("SELECT NOT 0=1, 1 BETWEEN 0 AND 2, 3 NOT BETWEEN 0 AND 2, CASE NULL WHEN NULL THEN 1 ELSE 2 END",[[1,1,1,2]])
check("SELECT 'abc' LIKE 'A%', 'æ' LIKE 'Æ', 'abc' GLOB 'a?c', 'a_c' LIKE 'a!_c' ESCAPE '!'",[[1,0,1,1]])
check("SELECT length('é🙂'), hex(x'00ABFF'), typeof(x'00'), hex(CAST('a' AS BLOB)), quote('a''b'), instr('éabc','a')",[[2,'00ABFF','blob','61',"'a''b'",2]])
check("SELECT substr('abcdef',-3,2),substr('abcdef',3,-2),substr('abcdef',0,3),trim('  a  '),round(1.235,2)",[['de','ab','ab','a','1.24']])
check("SELECT coalesce(NULL,2,3),nullif(1,1),iif(0,1,1,2,3),concat(NULL,'a',2),concat_ws(',',1,NULL,3)",[[2,None,2,'a2','1,3']])
check("SELECT date('2024-02-29','+1 year'),date('2024-02-29','+1 year','floor'),datetime(0,'unixepoch'),julianday('1970-01-01'),unixepoch('1970-01-02')",[['2025-03-01','2025-02-28','1970-01-01 00:00:00','2440587.5',86400]])
check("SELECT datetime('2013-10-07 04:23:19.120-04:00','subsec'),date('2024-02-15','start of month','+1 month','-1 day'),strftime('%Y-%m-%d %j %w %V','2024-01-01')",[['2013-10-07 08:23:19.120','2024-02-29','2024-01-01 001 1 01']])
check("SELECT timediff('2023-02-15','2023-03-15'),date('invalid'),strftime('%Q','2024-01-01')",[['-0000-01-00 00:00:00.000',None,None]])
check("SELECT json('{\"b\":2, \"a\":1}'),json_array(1,NULL,'x',json('[2,3]')),json_extract('{\"a\":null,\"b\":true}','$.a','$.b')",[['{"b":2,"a":1}','[1,null,"x",[2,3]]','[null,true]']])
check("SELECT json_set('{\"a\":1}','$.b[0]',2),json_extract('[10,20,30]','$[#-1]'),json_type('{\"a\":null}','$.a'),json_type('{}','$.missing'),json_valid('bad')",[['{"a":1,"b":[2]}',30,'null',None,0]])
check("SELECT '{\"a\":[1,2]}' -> 'a', '[1,2]' ->> -1, json_remove('[1,2,3]','$[1]')",[['[1,2]',2,'[1,3]']])
check("SELECT key,value,type,atom FROM json_each('[1,\"x\",null,[2]]')",[[0,1,'integer',1],[1,'x','text','x'],[2,None,'null',None],[3,'[2]','array',None]])
ok("CREATE TABLE t(id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT COLLATE NOCASE NOT NULL UNIQUE, val NUMERIC DEFAULT 4 CHECK(val>=0))")
ok("INSERT INTO t(name,val) VALUES('A','12'),('B',3.5),('C',NULL)")
check("SELECT id,typeof(val),val FROM t ORDER BY id",[[1,'integer',12],[2,'real','3.5'],[3,'null',None]])
err("INSERT INTO t(name,val) VALUES('D',8),('a',2)")
check("SELECT count(*) FROM t",[[3]])
ok("INSERT OR IGNORE INTO t(name,val) VALUES('a',2),('D',8)")
check("SELECT name FROM t ORDER BY id",[['A'],['B'],['C'],['D']])
ok("INSERT INTO t(name) VALUES('E')")
check("SELECT val FROM t WHERE name='e'",[[4]])
err("INSERT INTO t(name,val) VALUES('F',-1)")
err("INSERT INTO t(name) VALUES(NULL)")
check("SELECT * FROM t WHERE 0",[],columns=['id','name','val'])
err("SELECT bogus FROM t WHERE 0")
check("SELECT name FROM t WHERE val IN ('12','8') ORDER BY name",[['A'],['D']])
check("SELECT count(*), count(val), sum(val), total(val), avg(val), min(val),max(val) FROM t",[[5,4,'27.5','27.5','6.875','3.5',12]])
check("SELECT count(*),sum(val),total(val),avg(val),min(val) FROM t WHERE 0",[[0,None,'0.0',None,None]])
check("SELECT val IS NULL AS empty,count(*) AS n FROM t GROUP BY empty HAVING n>1 ORDER BY empty",[[0,4]])
check("SELECT name FROM t WHERE id IN (SELECT id FROM t WHERE val>5) ORDER BY name",[['A'],['D']])
check("SELECT a.name,(SELECT count(*) FROM t b WHERE b.id<a.id) FROM t a ORDER BY a.id",[['A',0],['B',1],['C',2],['D',3],['E',4]])
check("SELECT name FROM t ORDER BY val DESC NULLS FIRST LIMIT 2 OFFSET 1",[['A'],['D']])
check("SELECT 1 AS x UNION SELECT 1.0 UNION SELECT NULL ORDER BY x",[[None],[1]])
check("VALUES (1,'x'),(2,'y')",[[1,'x'],[2,'y']],columns=['column1','column2'])
check("WITH RECURSIVE seq(x) AS (VALUES(1) UNION ALL SELECT x+1 FROM seq WHERE x<10) SELECT sum(x) FROM seq",[[55]])
check("WITH x(a,b) AS (VALUES(1,2),(3,4)) SELECT a+b AS c FROM x ORDER BY c DESC",[[7],[3]])
check("SELECT name,row_number() OVER(ORDER BY val),rank() OVER(ORDER BY val),sum(val) OVER(ORDER BY val ROWS BETWEEN 1 PRECEDING AND CURRENT ROW) FROM t ORDER BY val",[['C',1,1,None],['B',2,2,'3.5'],['E',3,3,'7.5'],['D',4,4,12],['A',5,5,20]])
ok("CREATE TABLE a(id INT,v TEXT)");ok("CREATE TABLE b(id INT,w TEXT)")
ok("INSERT INTO a VALUES(1,'a'),(2,'b')");ok("INSERT INTO b VALUES(2,'x'),(3,'y')")
check("SELECT a.id,v,b.id,w FROM a LEFT JOIN b ON a.id=b.id ORDER BY a.id",[[1,'a',None,None],[2,'b',2,'x']])
check("SELECT * FROM a FULL JOIN b USING(id) ORDER BY id",[[1,'a',None],[2,'b','x'],[3,None,'y']])
check("SELECT a.id FROM a CROSS JOIN b WHERE a.id=b.id",[[2]])
err("SELECT id FROM a JOIN b ON a.id=b.id")
ok("CREATE VIEW vv AS SELECT name,val*2 AS doubled FROM t WHERE val>0")
check("SELECT name,doubled FROM vv WHERE name='E'",[['E',8]])
ok("CREATE TABLE copy AS SELECT * FROM a")
check("SELECT * FROM copy ORDER BY id",[[1,'a'],[2,'b']])
ok("BEGIN");ok("UPDATE t SET val=100 WHERE name='A'");ok("SAVEPOINT sp");ok("DELETE FROM t WHERE name='B'");ok("ROLLBACK TO sp")
check("SELECT val FROM t WHERE name='A'",[[100]])
ok("RELEASE sp");ok("ROLLBACK")
check("SELECT val FROM t WHERE name='A'",[[12]])
err("COMMIT")
ok("SAVEPOINT outer");ok("DELETE FROM copy");ok("RELEASE outer")
check("SELECT count(*) FROM copy",[[0]])
ok("BEGIN");ok("INSERT INTO copy VALUES(3,'c')");err("INSERT INTO t(name) VALUES('a')");ok("COMMIT")
check("SELECT * FROM copy",[[3,'c']])
check("INSERT INTO t(name,val) VALUES('A',17) ON CONFLICT(name) DO UPDATE SET val=excluded.val RETURNING name,val",[['A',17]])
ok("CREATE TABLE wr(a TEXT,b INT,c,PRIMARY KEY(a,b)) WITHOUT ROWID")
err("INSERT INTO wr VALUES(NULL,1,2)");ok("INSERT INTO wr VALUES('a',1,2)");err("SELECT rowid FROM wr")
ok("CREATE TABLE st(a INTEGER,b ANY,c TEXT) STRICT")
ok("INSERT INTO st VALUES('3','000123',4)")
check("SELECT a,typeof(b),b,c FROM st",[[3,'text','000123',4]])
err("INSERT INTO st VALUES('x',1,2)")
ok("CREATE TABLE gen(a INT,b INT GENERATED ALWAYS AS(a*2) STORED)")
ok("INSERT INTO gen(a) VALUES(3)");check("SELECT * FROM gen",[[3,6]])
ok("UPDATE gen SET a=4");check("SELECT * FROM gen",[[4,8]])
err("INSERT INTO gen(a,b) VALUES(1,2)")
ok("PRAGMA foreign_keys=ON")
ok("CREATE TABLE parent(id INTEGER PRIMARY KEY)")
ok("CREATE TABLE child(id INTEGER PRIMARY KEY,p INTEGER REFERENCES parent(id) ON DELETE CASCADE ON UPDATE CASCADE)")
err("INSERT INTO child VALUES(1,999)")
ok("INSERT INTO parent VALUES(1)");ok("INSERT INTO child VALUES(1,1)");ok("UPDATE parent SET id=2 WHERE id=1")
check("SELECT p FROM child",[[2]])
ok("DELETE FROM parent");check("SELECT count(*) FROM child",[[0]])
ok("CREATE TABLE def(p REFERENCES parent(id) DEFERRABLE INITIALLY DEFERRED)")
ok("BEGIN");ok("INSERT INTO def VALUES(9)");err("COMMIT");ok("INSERT INTO parent VALUES(9)");ok("COMMIT")
check("PRAGMA foreign_key_check",[])
ok("ALTER TABLE a ADD COLUMN extra TEXT DEFAULT 'z'");check("SELECT * FROM a ORDER BY id",[[1,'a','z'],[2,'b','z']])
ok("ALTER TABLE a RENAME COLUMN v TO label");check("SELECT label FROM a ORDER BY id",[['a'],['b']])
ok("ALTER TABLE a RENAME TO renamed");check("SELECT label FROM renamed ORDER BY id",[['a'],['b']])
path='/work/tests/persistence.db'
try: os.unlink(path)
except FileNotFoundError: pass
request({'op':'open','path':path})
ok('CREATE TABLE durable(id INTEGER PRIMARY KEY,t TEXT,b BLOB)');ok("INSERT INTO durable VALUES(1,'text',x'00FF')")
ok('PRAGMA user_version=42');ok('BEGIN');ok("INSERT INTO durable VALUES(2,'rollback',NULL)")
request({'op':'close'});request({'op':'open','path':path})
check('SELECT * FROM durable',[[1,'text','00FF']]);check('PRAGMA user_version',[[42]])
request({'op':'close'})
p.terminate();p.wait()
print(f'PASS: {n} documented SQL and persistence assertions')
